include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    sort_unnamed_constructors_first: ignore
# must_be_immutable: error
# sort_unnamed_constructors_first: ignore
